//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attending
    {
        public int StudentId { get; set; }
        public int LessonId { get; set; }
        public int ClassId { get; set; }
        public bool WasPresent { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual User Student { get; set; }
        public virtual Class Class { get; set; }
    }
}
