//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassStudent
    {
        public int UserId { get; set; }
        public int ClassId { get; set; }
        public System.DateTime JoinDate { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual User User { get; set; }
    }
}
