//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.Attendings = new HashSet<Attending>();
            this.Topics = new HashSet<Topic>();
        }
    
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public Nullable<short> ClassSize { get; set; }
        public double Frequency { get; set; }
        public Nullable<int> BinaryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attending> Attendings { get; set; }
        public virtual Binary Binary { get; set; }
        public virtual User Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual Class Class { get; set; }
    }
}
