//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AivEntities : DbContext
    {
        public AivEntities()
            : base("name=AivEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<ExerciseType> ExerciseTypes { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Edition> Editions { get; set; }
        public virtual DbSet<Binary> Binaries { get; set; }
    }
}
