//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submit
    {
        public int AssignmentId { get; set; }
        public int StudentId { get; set; }
        public int BinaryId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<byte> Score { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual Binary Binary { get; set; }
    }
}
