//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int AssignmentId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> BinaryId { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public Nullable<byte> Score { get; set; }
        public Nullable<int> RevisorId { get; set; }
    
        public virtual User Student { get; set; }
        public virtual User Revisor { get; set; }
        public virtual Assignment Assignment { get; set; }
        public virtual Binary Binary { get; set; }
    }
}
