//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLessonFullData
    {
        public int Id { get; set; }
        public int ClassId { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
        public Nullable<short> ClassSize { get; set; }
        public double Frequency { get; set; }
        public Nullable<int> BinaryId { get; set; }
        public string ClassName { get; set; }
        public short AcademicYear { get; set; }
        public string TeacherName { get; set; }
        public Nullable<int> StudentsCount { get; set; }
    }
}
