//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewClassIndex
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public Nullable<int> Students { get; set; }
        public Nullable<int> Lessons { get; set; }
        public Nullable<double> Frequency { get; set; }
        public int Points { get; set; }
        public bool IsClosed { get; set; }
    }
}
