
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace manager.aiv.it
{

using System;
    using System.Collections.Generic;
    
public partial class ViewStudentFullData
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Mobile { get; set; }

    public System.DateTime RegistrationDate { get; set; }

    public Nullable<int> ClassId { get; set; }

    public Nullable<int> BinaryId { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string Code { get; set; }

    public string ClassName { get; set; }

    public byte[] Picture { get; set; }

    public string PictureFileName { get; set; }

    public int NotesCount { get; set; }

}

}
