//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager.aiv.it
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLessonAttendancesAbsence
    {
        public int LessonId { get; set; }
        public Nullable<int> Attendances { get; set; }
        public Nullable<int> Absences { get; set; }
    }
}
